module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#006e2f",
        "secondary-fixed": "#ffddb8",
        "on-secondary-fixed": "#2a1700",
        "on-surface": "#e2e2e8",
        "tertiary-fixed-dim": "#ffb3ad",
        "on-primary-fixed": "#002109",
        "outline": "#869585",
        "secondary": "#ffb95f",
        "surface-container": "#1e2024",
        "on-tertiary-fixed-variant": "#930013",
        "secondary-container": "#ee9800",
        "error": "#ffb4ab",
        "surface-variant": "#333539",
        "surface-dim": "#111317",
        "on-surface-variant": "#bccbb9",
        "surface-container-highest": "#333539",
        "primary-container": "#22c55e",
        "on-primary-container": "#004b1e",
        "tertiary": "#ffb4ae",
        "inverse-on-surface": "#2f3035",
        "primary": "#4be277",
        "on-secondary-container": "#5b3800",
        "on-secondary-fixed-variant": "#653e00",
        "surface-tint": "#4ae176",
        "primary-fixed": "#6bff8f",
        "background": "#111317",
        "error-container": "#93000a",
        "inverse-surface": "#e2e2e8",
        "primary-fixed-dim": "#4ae176",
        "on-primary-fixed-variant": "#005321",
        "tertiary-fixed": "#ffdad7",
        "on-tertiary-fixed": "#410004",
        "surface": "#111317",
        "surface-bright": "#37393e",
        "surface-container-lowest": "#0c0e12",
        "on-error": "#690005",
        "on-error-container": "#ffdad6",
        "outline-variant": "#3d4a3d",
        "on-primary": "#003915",
        "surface-container-low": "#1a1c20",
        "on-secondary": "#472a00",
        "on-tertiary-container": "#860011",
        "tertiary-container": "#ff8a83",
        "on-tertiary": "#68000a",
        "secondary-fixed-dim": "#ffb95f",
        "on-background": "#e2e2e8",
        "surface-container-high": "#282a2e"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "sm": "8px",
        "base": "4px",
        "md": "16px",
        "lg": "24px",
        "xl": "32px",
        "gutter": "12px",
        "xs": "4px"
      },
      fontFamily: {
        "data-mono": ["JetBrains Mono", "monospace"],
        "body-base": ["Hanken Grotesk", "sans-serif"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "data-mono-bold": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "body-sm": ["Hanken Grotesk", "sans-serif"],
        "label-caps": ["Hanken Grotesk", "sans-serif"]
      },
      fontSize: {
        "data-mono": ["13px", { "lineHeight": "18px", "letterSpacing": "0em", "fontWeight": "450" }],
        "body-base": ["14px", { "lineHeight": "20px", "letterSpacing": "-0.01em", "fontWeight": "400" }],
        "headline-md": ["18px", { "lineHeight": "24px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "data-mono-bold": ["13px", { "lineHeight": "18px", "letterSpacing": "0em", "fontWeight": "600" }],
        "headline-lg": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "body-sm": ["13px", { "lineHeight": "18px", "letterSpacing": "0em", "fontWeight": "400" }],
        "label-caps": ["11px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
