environment: production

logging:
  directory: volume/logs

volume: /opt/bgpalerter/volume

monitoredPrefixesFiles:
  - prefixes.yml

connectors:
  - file: connectorRIS
    name: ris

monitors:
  - file: monitorHijack
    channel: hijack
    
  - file: monitorPath
    channel: path
    
  - file: monitorVisibility
    channel: visibility
    
  - file: monitorNewPrefix
    channel: newprefix
    
  - file: monitorAS
    channel: asn

reports:
  - file: reportFile
    channels:
      - hijack
      - newprefix
      - visibility
      - path
      - asn

  - file: reportHTTP
    channels:
      - hijack
      - newprefix
      - visibility
      - path
      - asn
    params:
      hooks:
        - channel: hijack
          url: http://backend:8000/api/bgpalerter/webhook/hijack
        - channel: newprefix
          url: http://backend:8000/api/bgpalerter/webhook/newprefix
        - channel: visibility
          url: http://backend:8000/api/bgpalerter/webhook/visibility
        - channel: path
          url: http://backend:8000/api/bgpalerter/webhook/path
        - channel: asn
          url: http://backend:8000/api/bgpalerter/webhook/asn
