connectors:
  - file: connectorRIS
    name: ris
    params:
      url: ws://ris-live.ripe.net/v1/ws/
      perMessageDeflate: true

monitors:
  - file: monitorHijack
    channel: hijack
    params:
      thresholdMinPeers: 3

  - file: monitorPath
    channel: path
    params:
      thresholdMinPeers: 1

  - file: monitorVisibility
    channel: visibility
    params:
      thresholdMinPeers: 10
      notificationIntervalSeconds: 3600

  - file: monitorNewPrefix
    channel: newprefix
    params:
      thresholdMinPeers: 3

  - file: monitorAS
    channel: misconfiguration
    params:
      thresholdMinPeers: 3

reports:
  - file: reportFile
    channels:
      - hijack
      - newprefix
      - visibility
      - path
      - misconfiguration

  - file: reportHTTP
    channels:
      - hijack
      - newprefix
      - visibility
      - path
      - misconfiguration
    params:
      hooks:
        - channel: hijack
          url: http://backend:8000/api/bgpalerter/webhook/hijack
        - channel: newprefix
          url: http://backend:8000/api/bgpalerter/webhook/newprefix
        - channel: visibility
          url: http://backend:8000/api/bgpalerter/webhook/visibility
        - channel: path
          url: http://backend:8000/api/bgpalerter/webhook/path
        - channel: misconfiguration
          url: http://backend:8000/api/bgpalerter/webhook/asn

environment: production
volume: /opt/bgpalerter/volume
monitoredPrefixesFiles:
  - prefixes.yml

logging:
  directory: volume/logs

processMonitors: false

checkForUpdatesAtBoot: false
