# BGPalerter Configuration for IRRExplorer Integration
# Compatible with BGPalerter v2.0.1+

environment: production

# Volume directory for persistent data
volume: /opt/bgpalerter/volume

# Logging configuration
logging:
  level: info
  directory: volume/logs
  logRotatePattern: YYYY-MM-DD
  maxRetainedFiles: 10
  compressOldFiles: false

# Prefix files configuration
monitoredPrefixesFiles:
  - prefixes.yml

# RPKI configuration
rpki:
  vrps: https://console.rpki-client.org/vrps.json

# BGP data sources
connectors:
  - file: connectorRIS
    name: ris
    params:
      carefulInitialPrefixLoading: true

# Monitoring modules
monitors:
  - file: monitorHijack
    channel: hijack
    params:
      thresholdMinPeers: 2

  - file: monitorPath
    channel: path
    params:
      thresholdMinPeers: 2

  - file: monitorVisibility
    channel: visibility
    params:
      thresholdMinPeers: 2

  - file: monitorNewPrefix
    channel: newprefix
    params:
      thresholdMinPeers: 2

  - file: monitorRPKI
    channel: rpki

# Reports configuration (notifications)
reports:
  - file: reportFile
    channels:
      - hijack
      - newprefix
      - visibility
      - path
      - rpki
    params:
      showPaths: 0
      persistAlertData: true

  - file: reportHTTP
    channels:
      - hijack
      - newprefix
      - visibility
      - path
      - rpki
    params:
      templates:
        default: "New BGP alert"
      hooks:
        - channel: hijack
          url: http://backend:8000/api/bgpalerter/webhook/hijack
          method: POST
          headers:
            Content-Type: application/json
        - channel: newprefix
          url: http://backend:8000/api/bgpalerter/webhook/newprefix
          method: POST
          headers:
            Content-Type: application/json
        - channel: visibility
          url: http://backend:8000/api/bgpalerter/webhook/visibility
          method: POST
          headers:
            Content-Type: application/json
        - channel: path
          url: http://backend:8000/api/bgpalerter/webhook/path
          method: POST
          headers:
            Content-Type: application/json
        - channel: rpki
          url: http://backend:8000/api/bgpalerter/webhook/rpki
          method: POST
          headers:
            Content-Type: application/json

# Notification settings
notification:
  notificationIntervalSeconds: 7200

# API server configuration
rest:
  host: "0.0.0.0"
  port: 8011
