apiVersion: v1
kind: Service
metadata:
  name: {{ include "irrexplorer.backendServiceName" . }}
  labels:
    {{- include "irrexplorer.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "irrexplorer.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: {{ .Values.backend.service.port }}
      targetPort: http
