apiVersion: v1
kind: Secret
metadata:
  name: {{ include "irrexplorer.fullname" . }}-app
  labels:
    {{- include "irrexplorer.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "irrexplorer.databaseUrl" . | quote }}
  REDIS_URL: {{ include "irrexplorer.redisUrl" . | quote }}
  JWT_SECRET_KEY: {{ .Values.config.jwtSecretKey | quote }}
